### ISSUE TITLE
Loading "Gruntfile.js" tasks...ERROR

### ISSUE THREAD

**Issue by pienisieni** [silvermine/videojs-airplay#31]
I run into problems in "Building the plugin locally" steps 2 & 3.

I've just cloned the repository and ran into this:

```
npm install

> node-sass@4.13.1 install /home/runcloud/webapps/kuu/kato/videojs-airplay-master/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.1/linux-x64-57_binding.node
Download complete .] - :
Binary saved to /home/runcloud/webapps/kuu/kato/videojs-airplay-master/node_modules/node-sass/vendor/linux-x64-57/binding.node
Caching binary to /home/runcloud/.npm/node-sass/4.13.1/linux-x64-57_binding.node

> core-js@2.6.11 postinstall /home/runcloud/webapps/kuu/kato/videojs-airplay-master/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> node-sass@4.13.1 postinstall /home/runcloud/webapps/kuu/kato/videojs-airplay-master/node_modules/node-sass
> node scripts/build.js

Binary found at /home/runcloud/webapps/kuu/kato/videojs-airplay-master/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> @silvermine/videojs-airplay@1.0.1 prepublish /home/runcloud/webapps/kuu/kato/videojs-airplay-master
> grunt build

fatal: not a git repository (or any of the parent directories): .git
Loading "Gruntfile.js" tasks...ERROR
>> Error: Command failed: git describe --always --dirty --tags
>> fatal: not a git repository (or any of the parent directories): .git
Warning: Task "build" not found. Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! @silvermine/videojs-airplay@1.0.1 prepublish: `grunt build`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the @silvermine/videojs-airplay@1.0.1 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runcloud/.npm/_logs/2020-12-17T11_24_34_961Z-debug.log

grunt build
module.js:550
    throw err;
    ^
```

As for step 3.

```
grunt build

Error: Cannot find module 'findup-sync'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/nodejs/grunt-cli/bin/grunt:8:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

FYI:

```
uname -a
Linux kuu 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```

The log file:
[2020-12-17T11_26_14_504Z-debug.log](https://kuu.73x45.com/files/2020-12-17T11_26_14_504Z-debug.log)

Thank you.

**Comment by pienisieni** [comment]
Gave up on this and instead decided to just turn off Airplay.

`x-webkit-airplay="deny"`
